### ISSUE TITLE
Workflows clang-format and linux_build are duplicated for PRs

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9008]
Issue overview
--------------
https://github.com/NREL/EnergyPlus/blob/82391071e9a009712653ee6017118dce65dacf90/.github/workflows/clang-format-check.yml#L1-L2

https://github.com/NREL/EnergyPlus/blob/82391071e9a009712653ee6017118dce65dacf90/.github/workflows/linux_build.yml#L1-L3

if I open a PR, it does it twice!

I would do something different, like on push to develop or PRs to develop:

```
on:
  push:
    branches: [ develop ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ develop ]
```

Or, if you really want it on every commit then just  `on: [push]` would be enough.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
